name: book_store
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # API call
  dio: ^5.5.0
  retrofit: ^4.0.1
  json_annotation: ^4.8.1

  # State management
  flutter_bloc: ^8.1.6

  # Image rendering
  cached_network_image: ^3.4.1

  # Responsive
  device_preview: ^1.2.0

  # For icons
  font_awesome_flutter: ^10.7.0

  # Animation
  animations: ^2.0.11
  lottie: ^3.0.0

  # Rating bar
  flutter_rating_bar: ^4.0.1

  # Connect with local
  shared_preferences: ^2.2.2

  # Dependency Injection
  get_it: ^7.2.0

  cupertino_icons: ^1.0.6
  meta: ^1.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  retrofit_generator: ^7.0.1
  build_runner: ^2.3.3
  json_serializable: ^6.6.2
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo/logo_forground.png"


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/home_screen/
     - assets/images/welcome_screen/
     - assets/animations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
